---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: d039aa898a2eee2ba22671454648ae0702bb4d41
    app.quarkus.io/build-timestamp: 2022-11-03 - 05:05:13 +0000
  labels:
    app.kubernetes.io/name: inner-outer-repo
    app.kubernetes.io/version: "2.0"
    app.openshift.io/runtime: quarkus
  name: inner-outer-repo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: inner-outer-repo
    app.kubernetes.io/version: "2.0"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: d039aa898a2eee2ba22671454648ae0702bb4d41
    app.quarkus.io/build-timestamp: 2022-11-03 - 05:05:13 +0000
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: inner-outer-repo
    app.kubernetes.io/version: "2.0"
  name: inner-outer-repo
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: inner-outer-repo
      app.kubernetes.io/version: "2.0"
  template:
    metadata:
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: inner-outer-repo
        app.kubernetes.io/version: "2.0"
    spec:
      containers:
        - image: quay.io/rh_ee_mbastug/inner-outer-repo:2.0
          imagePullPolicy: Always
          name: inner-outer-repo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
